version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    # volumes:
    #   - ./backend:/app # For development: reflects code changes live
    networks:
      - vocalis-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.gradio
    ports:
      - "7860:7860"
    environment:
      - FASTAPI_WS_URL=ws://backend:8000/ws
    # volumes:
    #  - ./gradio_app.py:/app/gradio_app.py # For development
    depends_on:
      - backend
    networks:
      - vocalis-net

networks:
  vocalis-net:
    driver: bridge
